language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t eduarcos/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true eduarcos/react-test npm test

after_success:
    - docker build -t eduarcos/multi-client ./client
    - docker build -t eduarcos/multi-nginx ./nginx
    - docker build -t eduarcos/multi-server ./server
    - docker build -t eduarcos/multi-worker ./worker
    # Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker-hub
    - docker push eduarcos/multi-client
    - docker push eduarcos/multi-nginx
    - docker push eduarcos/multi-server
    - docker push eduarcos/multi-worker

# deploy:
#     provide: elasticbeanstalk
#     region: eu-central-1
#     app: multi-docker
#     env: MultiDocker-env
#     bucket_name: elasticbeanstalk-eu-central-1-820661781237
#     bucket_path: docker-multi
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY